### ISSUE TITLE
Error: Cannot find module '../build/Debug/nodegit.node'

### ISSUE THREAD

**Issue by davidfekke** [diegohaz/nod#7]
I get the following error when I try to `yo nod`.

Error: Cannot find module '../build/Debug/nodegit.node'

Here is the full text of the error;
```
module.js:472
    throw err;
    ^

Error: Cannot find module '../build/Debug/nodegit.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/davidfekke/Documents/node/projects/samplemod/node_modules/nodegit/dist/nodegit.js:18:12)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by diegohaz** [comment]
Seems to be related to https://github.com/nodegit/nodegit/issues/1134

Could you try `sudo xcode-select --install` as stated in https://github.com/nodegit/nodegit/issues/1134#issuecomment-283672798 and reinstall `generator-nod`?

**Comment by diegohaz** [comment]
It should be fixed in `v0.3.0`

**Comment by cmdcolin** [comment]
Just a random note but I was getting this error probably due to nodegit was failing on linux and wsl for me (hanging indefinitely). I tried following advice from that thread like `sudo apt install libcurl4-openssl-dev` but the nodegit postinstall step was still failing wiith a segmentation fault

I have not yet fixed the issue but I don't think it's a bug with your module
